# Generated by Django 6.0.6 on 2026-07-28 07:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0017_transactionverification'),
        ('mills', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='millingreport',
            name='harvest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='milling_reports', to='farmers.harvest'),
        ),
        migrations.AddField(
            model_name='millingreport',
            name='paddy_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='milling_reports', to='farmers.paddytype'),
        ),
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_date', models.DateField(auto_now_add=True)),
                ('result', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('needs_follow_up', 'Needs Follow-up')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('mill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='mills.mill')),
                ('officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-inspection_date'],
            },
        ),
    ]
