# Generated by Django 6.0.6 on 2026-08-04 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mills', '0002_millingreport_harvest_millingreport_paddy_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='mill_license_documents/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='license',
            name='renewed_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renewals', to='mills.license'),
        ),
        migrations.AddField(
            model_name='millingreport',
            name='bran_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='millingreport',
            name='husk_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='license',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('suspended', 'Suspended'), ('revoked', 'Revoked')], default='pending', max_length=20),
        ),
    ]
