# Generated by Django 6.0.6 on 2026-08-04 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mills', '0003_license_document_license_renewed_from_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='license',
            name='document',
        ),
        migrations.AddField(
            model_name='license',
            name='contact_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='license',
            name='justification',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='license',
            name='milling_type',
            field=models.CharField(blank=True, choices=[('raw', 'Raw'), ('parboiled', 'Parboiled'), ('both', 'Both')], max_length=10),
        ),
        migrations.AddField(
            model_name='license',
            name='premises_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='license',
            name='requested_capacity_mt_per_day',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
