# Generated by Django 6.0.6 on 2026-08-04 09:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0022_deliveryslot'),
        ('mills', '0004_remove_license_document_license_contact_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MillingAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_kg', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('fulfilled', 'Fulfilled')], default='pending', max_length=20)),
                ('requested_date', models.DateTimeField(auto_now_add=True)),
                ('review_notes', models.TextField(blank=True)),
                ('fulfilled_from_warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fulfilled_milling_allocations', to='farmers.warehouse')),
                ('mill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milling_allocations', to='mills.mill')),
                ('paddy_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='milling_allocations', to='farmers.paddytype')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_milling_allocations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-requested_date'],
            },
        ),
        migrations.AddField(
            model_name='millingreport',
            name='allocation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='milling_reports', to='mills.millingallocation'),
        ),
        migrations.CreateModel(
            name='MillingReturnRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rice_kg', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('dispatched', 'Dispatched'), ('delivered', 'Delivered')], default='pending', max_length=20)),
                ('requested_date', models.DateTimeField(auto_now_add=True)),
                ('review_notes', models.TextField(blank=True)),
                ('allocation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_requests', to='mills.millingallocation')),
                ('destination_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_milling_returns', to='farmers.warehouse')),
                ('mill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_requests', to='mills.mill')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_milling_returns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-requested_date'],
            },
        ),
        migrations.CreateModel(
            name='MillStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_kg', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('mill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_entries', to='mills.mill')),
                ('paddy_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mill_stocks', to='farmers.paddytype')),
            ],
            options={
                'unique_together': {('mill', 'paddy_type')},
            },
        ),
    ]
