# Generated by Django 6.0.6 on 2026-08-13 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mills', '0005_millingallocation_millingreport_allocation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='contact_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='license',
            name='justification',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='license',
            name='milling_type',
            field=models.CharField(blank=True, choices=[('raw', 'Raw'), ('parboiled', 'Parboiled'), ('both', 'Both')], max_length=10),
        ),
        migrations.AddField(
            model_name='license',
            name='premises_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='license',
            name='renewed_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renewals', to='mills.license'),
        ),
        migrations.AddField(
            model_name='license',
            name='requested_capacity_mt_per_day',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='millingreport',
            name='bran_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='millingreport',
            name='husk_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='license',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('suspended', 'Suspended'), ('revoked', 'Revoked')], default='pending', max_length=20),
        ),
    ]
