# Generated by Django 6.0.6 on 2026-07-21 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0003_harvest_grade_harvest_moisture_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmer',
            name='bank_account',
        ),
        migrations.RemoveField(
            model_name='farmer',
            name='bank_name',
        ),
    ]
