# Generated by Django 6.0.6 on 2026-07-22 22:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0004_remove_farmer_bank_account_remove_farmer_bank_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('license_no', models.CharField(max_length=30, unique=True)),
                ('contact_number', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('on_duty', 'On Duty'), ('off_duty', 'Off Duty'), ('inactive', 'Inactive')], default='available', max_length=20)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=200)),
                ('destination', models.CharField(max_length=200)),
                ('distance_km', models.DecimalField(decimal_places=2, max_digits=8)),
                ('estimated_time', models.CharField(blank=True, help_text='e.g. 3h 20m', max_length=50)),
            ],
            options={
                'ordering': ['origin', 'destination'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_no', models.CharField(max_length=30, unique=True)),
                ('vehicle_type', models.CharField(choices=[('lorry', 'Lorry'), ('van', 'Van'), ('tractor', 'Tractor'), ('three_wheeler', 'Three Wheeler'), ('pickup', 'Pickup'), ('other', 'Other')], default='lorry', max_length=20)),
                ('capacity_kg', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('maintenance', 'Under Maintenance'), ('retired', 'Retired')], default='active', max_length=20)),
            ],
            options={
                'ordering': ['registration_no'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_date', models.DateField()),
                ('description', models.CharField(blank=True, max_length=255)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('next_service_date', models.DateField(blank=True, null=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='farmers.vehicle')),
            ],
            options={
                'ordering': ['-service_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='FuelRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel_type', models.CharField(choices=[('petrol', 'Petrol'), ('diesel', 'Diesel'), ('cng', 'CNG')], default='diesel', max_length=20)),
                ('quantity_litres', models.DecimalField(decimal_places=2, max_digits=8)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fuel_date', models.DateField()),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_records', to='farmers.vehicle')),
            ],
            options={
                'ordering': ['-fuel_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('delayed', 'Delayed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='farmers.warehouse')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='farmers.driver')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='farmers.route')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='farmers.vehicle')),
            ],
            options={
                'ordering': ['-scheduled_date', '-id'],
            },
        ),
    ]
