# Generated by Django 6.0.6 on 2026-07-26 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0013_harvest_processed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='notify_harvest_updates',
            field=models.BooleanField(default=True),
        ),
    ]
