# Generated by Django 6.0.6 on 2026-08-02 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0017_transactionverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='reliability_score',
            field=models.FloatField(default=0),
        ),
    ]
