# Generated by Django 6.0.6 on 2026-08-02 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0018_farmer_reliability_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='notify_via_sms',
            field=models.BooleanField(default=False),
        ),
    ]
