# Generated by Django 6.0.6 on 2026-08-02 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0019_farmer_notify_via_sms'),
    ]

    operations = [
        migrations.AddField(
            model_name='harvest',
            name='lot_code',
            field=models.CharField(blank=True, db_index=True, max_length=30, null=True, unique=True),
        ),
    ]
