# Generated by Django 6.0.6 on 2026-08-04 06:43

from django.db import migrations, models


def backfill_price_record_season(apps, schema_editor):
    """Existing PriceRecord rows got the 'yala' field default on add — recompute the real season from each row's effective_date."""
    PriceRecord = apps.get_model('farmers', 'PriceRecord')
    for record in PriceRecord.objects.all():
        season = 'yala' if 4 <= record.effective_date.month <= 8 else 'maha'
        if record.season != season:
            record.season = season
            record.save(update_fields=['season'])


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0020_harvest_lot_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='bank_branch',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='harvest',
            name='empty_grains_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='harvest',
            name='impurity_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='pricerecord',
            name='season',
            field=models.CharField(choices=[('yala', 'Yala'), ('maha', 'Maha')], default='yala', max_length=10),
        ),
        migrations.RunPython(backfill_price_record_season, migrations.RunPython.noop),
    ]
