# Generated by Django 6.0.6 on 2026-08-03 07:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0020_harvest_lot_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionlog',
            name='transaction_type',
            field=models.CharField(choices=[('harvest_collection', 'Harvest Collection'), ('rice_request_fulfillment', 'Rice Request Fulfillment'), ('manual_adjustment', 'Manual Adjustment'), ('transfer_out', 'Transfer Out'), ('transfer_in', 'Transfer In')], max_length=30),
        ),
        migrations.CreateModel(
            name='WarehouseTransferRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(blank=True, choices=[('A', 'Grade A'), ('B', 'Grade B'), ('C', 'Grade C')], max_length=1, null=True)),
                ('quantity_kg', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('review_notes', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('requested_date', models.DateTimeField(auto_now_add=True)),
                ('resolved_date', models.DateTimeField(blank=True, null=True)),
                ('from_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_transfer_requests', to='farmers.warehouse')),
                ('paddy_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='warehouse_transfer_requests', to='farmers.paddytype')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('to_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_transfer_requests', to='farmers.warehouse')),
            ],
            options={
                'ordering': ['-requested_date'],
            },
        ),
        migrations.AddField(
            model_name='transactionlog',
            name='transfer_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_logs', to='farmers.warehousetransferrequest'),
        ),
    ]
