# Generated by Django 6.0.6 on 2026-08-04 09:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0022_deliveryslot'),
        ('mills', '0005_millingallocation_millingreport_allocation_and_more'),
        ('purchases', '0004_dispatchmanifest_farmgatepurchase'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='dispatch_manifest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='purchases.dispatchmanifest'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='milling_return_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='mills.millingreturnrequest'),
        ),
        migrations.AddField(
            model_name='payment',
            name='disbursed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='disbursement_reference',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('disbursed', 'Disbursed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='transactionlog',
            name='transaction_type',
            field=models.CharField(choices=[('harvest_collection', 'Harvest Collection'), ('rice_request_fulfillment', 'Rice Request Fulfillment'), ('manual_adjustment', 'Manual Adjustment'), ('milling_allocation_fulfillment', 'Milling Allocation Fulfillment'), ('dispatch_manifest_delivery', 'Dispatch Manifest Delivery'), ('milling_return_delivery', 'Milling Return Delivery')], max_length=30),
        ),
        migrations.AddField(
            model_name='deliveryslot',
            name='checked_in_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deliveryslot',
            name='farmer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_slots', to='farmers.farmer'),
        ),
        migrations.AddField(
            model_name='deliveryslot',
            name='paddy_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_slots', to='farmers.paddytype'),
        ),
        migrations.AddField(
            model_name='deliveryslot',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_slots', to='farmers.warehouse'),
        ),
        migrations.AddField(
            model_name='harvest',
            name='delivery_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='harvests', to='farmers.deliveryslot'),
        ),
    ]
