# Generated by Django 6.0.6 on 2026-08-10 21:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0023_deliveryslot'),
        ('mills', '0003_millingallocation_millingreturnrequest_millstock'),
        ('purchases', '0003_authorizedpurchaser_advance_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='dispatch_manifest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='purchases.dispatchmanifest'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='milling_return_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='mills.millingreturnrequest'),
        ),
        migrations.AlterField(
            model_name='transactionlog',
            name='transaction_type',
            field=models.CharField(choices=[('harvest_collection', 'Harvest Collection'), ('rice_request_fulfillment', 'Rice Request Fulfillment'), ('manual_adjustment', 'Manual Adjustment'), ('transfer_out', 'Transfer Out'), ('transfer_in', 'Transfer In'), ('milling_allocation_fulfillment', 'Milling Allocation Fulfillment'), ('dispatch_manifest_delivery', 'Dispatch Manifest Delivery'), ('milling_return_delivery', 'Milling Return Delivery')], max_length=30),
        ),
        migrations.AddField(
            model_name='deliveryslot',
            name='checked_in_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deliveryslot',
            name='farmer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_slots', to='farmers.farmer'),
        ),
        migrations.AddField(
            model_name='deliveryslot',
            name='paddy_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_slots', to='farmers.paddytype'),
        ),
        migrations.AddField(
            model_name='deliveryslot',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_slots', to='farmers.warehouse'),
        ),
        migrations.AddField(
            model_name='harvest',
            name='delivery_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='harvests', to='farmers.deliveryslot'),
        ),
    ]
