# Generated by Django 6.0.6 on 2026-08-13 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0023_delivery_dispatch_manifest_and_more'),
        ('mills', '0005_millingallocation_millingreport_allocation_and_more'),
        ('purchases', '0005_authorizedpurchaser_nic'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='milling_allocation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='mills.millingallocation'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='rice_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='purchases.ricerequest'),
        ),
    ]
