# Generated by Django 6.0.6 on 2026-08-13 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0025_delivery_reminder_sent_at_delivery_scheduled_time_and_more'),
        ('mills', '0006_license_contact_number_license_justification_and_more'),
        ('purchases', '0005_authorizedpurchaser_nic'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='milling_allocation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='mills.millingallocation'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='rice_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='purchases.ricerequest'),
        ),
        migrations.AddField(
            model_name='farmer',
            name='bank_branch',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='harvest',
            name='empty_grains_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='harvest',
            name='impurity_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='disbursed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='disbursement_reference',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='pricerecord',
            name='season',
            field=models.CharField(choices=[('yala', 'Yala'), ('maha', 'Maha')], default='yala', max_length=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('disbursed', 'Disbursed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
