# Generated by Django 6.0.6 on 2026-08-13 23:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0027_delivery_received_at_delivery_received_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='accepted_reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fuelrecord',
            name='delivery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fuel_records', to='farmers.delivery'),
        ),
        migrations.AddField(
            model_name='fuelrecord',
            name='price_per_litre',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='maintenancerecord',
            name='next_service_due_km',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maintenancerecord',
            name='odometer_km',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maintenancerecord',
            name='service_type',
            field=models.CharField(choices=[('oil_change', 'Oil Change'), ('tire_service', 'Tire Replacement/Rotation'), ('brake_service', 'Brake Service'), ('battery_replacement', 'Battery Replacement'), ('air_filter', 'Air Filter Replacement'), ('fuel_filter', 'Fuel Filter Replacement'), ('coolant_service', 'Coolant/Radiator Service'), ('clutch_transmission', 'Clutch/Transmission Service'), ('suspension_service', 'Suspension/Shock Absorber Service'), ('wheel_alignment', 'Wheel Alignment & Balancing'), ('ac_service', 'AC Service'), ('general_inspection', 'General Inspection'), ('other', 'Other')], default='other', max_length=30),
        ),
    ]
