# Generated by Django 6.0.6 on 2026-07-23 20:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farmers', '0004_remove_farmer_bank_account_remove_farmer_bank_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_kg', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('fulfilled', 'Fulfilled')], default='pending', max_length=20)),
                ('requested_date', models.DateTimeField(auto_now_add=True)),
                ('review_notes', models.TextField(blank=True)),
                ('fulfilled_from_warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fulfilled_rice_requests', to='farmers.warehouse')),
                ('paddy_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rice_requests', to='farmers.paddytype')),
                ('purchaser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rice_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_rice_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-requested_date'],
            },
        ),
        migrations.CreateModel(
            name='PurchaserStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_kg', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('paddy_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchaser_stocks', to='farmers.paddytype')),
                ('purchaser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('purchaser', 'paddy_type')},
            },
        ),
    ]
