# Generated by Django 6.0.6 on 2026-08-04 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0002_authorized_purchaser_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorizedpurchaser',
            name='advance_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='authorizedpurchaser',
            name='weight_limit_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
