# Generated by Django 6.0.6 on 2026-08-13 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0004_dispatchmanifest_farmgatepurchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorizedpurchaser',
            name='nic',
            field=models.CharField(default='', max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
