# Generated by Django 6.0.6 on 2026-08-13 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0005_authorizedpurchaser_nic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ricerequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('fulfilled', 'Fulfilled'), ('received', 'Received')], default='pending', max_length=20),
        ),
    ]
