# Generated by Django 6.0.6 on 2026-07-22 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0008_remove_old_driver_field'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delivery',
            old_name='driver_user',
            new_name='driver',
        ),
    ]
