# Generated by Django 6.0.6 on 2026-07-22 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0009_rename_driver_user_to_driver'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Driver',
        ),
    ]
