# Generated by Django 6.0.6 on 2026-07-23 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0011_delivery_assignment_status_deliverylocationping'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='manufacture_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='model',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='size',
            field=models.CharField(blank=True, help_text='Body size/dimensions, e.g. "14ft", "6-wheeler".', max_length=50),
        ),
    ]
