# Generated by Django 5.0.9 on 2026-07-09 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PmbOfficer',
            fields=[
                ('pmb_officer_id', models.AutoField(db_column='pmb_officer_id', primary_key=True, serialize=False)),
                ('employee_no', models.CharField(blank=True, default='', max_length=50)),
                ('name', models.CharField(max_length=150)),
                ('nic', models.CharField(blank=True, default='', max_length=20)),
                ('role', models.CharField(blank=True, default='', max_length=50)),
                ('designation', models.CharField(blank=True, default='', max_length=100)),
                ('location', models.CharField(blank=True, default='', max_length=200)),
                ('district', models.CharField(blank=True, default='', max_length=100)),
                ('contact_number', models.CharField(blank=True, default='', max_length=50)),
                ('email', models.CharField(blank=True, default='', max_length=150)),
                ('joined_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, default='', max_length=50)),
            ],
            options={
                'db_table': 'pmb_officer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PurchaseIntake',
            fields=[
                ('purchase_id', models.AutoField(db_column='purchase_id', primary_key=True, serialize=False)),
                ('purchase_number', models.CharField(blank=True, default='', max_length=50)),
                ('purchase_date', models.DateTimeField(blank=True, null=True)),
                ('paddy_type', models.CharField(blank=True, default='', max_length=100)),
                ('grade', models.CharField(blank=True, default='', max_length=50)),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('payment_method', models.CharField(blank=True, default='', max_length=50)),
                ('payment_status', models.CharField(blank=True, default='', max_length=50)),
                ('moisture_level', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('quality_checked', models.BooleanField(blank=True, null=True)),
                ('farmer_id', models.IntegerField(blank=True, null=True)),
                ('purchaser_id', models.IntegerField(blank=True, null=True)),
                ('warehouse_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'purchase_intake',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('warehouse_id', models.AutoField(db_column='warehouse_id', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(blank=True, default='', max_length=50)),
                ('capacity', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('current_stock', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('location', models.CharField(blank=True, default='', max_length=200)),
                ('district', models.CharField(blank=True, default='', max_length=100)),
                ('province', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.CharField(blank=True, default='', max_length=50)),
                ('contact_number', models.CharField(blank=True, default='', max_length=50)),
                ('established_date', models.DateField(blank=True, null=True)),
                ('managed_by_pmb_officer_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'warehouse',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('driver_id', models.AutoField(db_column='driver_id', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('license_no', models.CharField(max_length=30, unique=True)),
                ('contact_no', models.CharField(blank=True, default='', max_length=30)),
                ('address', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('available', 'Available'), ('on_duty', 'On Duty'), ('off_duty', 'Off Duty'), ('inactive', 'Inactive')], default='available', max_length=20)),
            ],
            options={
                'db_table': 'driver',
                'ordering': ['driver_id'],
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('route_id', models.AutoField(db_column='route_id', primary_key=True, serialize=False)),
                ('origin', models.CharField(max_length=200)),
                ('destination', models.CharField(max_length=200)),
                ('distance', models.FloatField(help_text='Distance in kilometres')),
                ('estimated_time', models.CharField(blank=True, default='', help_text='Estimated travel time (e.g. 3h 20m)', max_length=50)),
            ],
            options={
                'db_table': 'route',
                'ordering': ['route_id'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('vehicle_id', models.AutoField(db_column='vehicle_id', primary_key=True, serialize=False)),
                ('registration_no', models.CharField(max_length=30, unique=True)),
                ('vehicle_type', models.CharField(choices=[('lorry', 'Lorry'), ('van', 'Van'), ('tractor', 'Tractor'), ('three_wheeler', 'Three Wheeler'), ('pickup', 'Pickup'), ('other', 'Other')], default='lorry', max_length=20)),
                ('capacity', models.IntegerField(help_text='Carrying capacity in kilograms (kg)')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('maintenance', 'Under Maintenance'), ('retired', 'Retired')], default='active', max_length=20)),
            ],
            options={
                'db_table': 'vehicle',
                'ordering': ['vehicle_id'],
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('delivery_id', models.AutoField(db_column='delivery_id', primary_key=True, serialize=False)),
                ('scheduled_date', models.DateField(blank=True, null=True)),
                ('delivery_status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('delayed', 'Delayed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('approved_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='logistics.pmbofficer')),
                ('purchase', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='logistics.purchaseintake')),
                ('warehouse', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='logistics.warehouse')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='logistics.driver')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='logistics.route')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='logistics.vehicle')),
            ],
            options={
                'db_table': 'delivery',
                'ordering': ['-scheduled_date', 'delivery_id'],
            },
        ),
        migrations.CreateModel(
            name='GpsTracking',
            fields=[
                ('tracking_id', models.AutoField(db_column='tracking_id', primary_key=True, serialize=False)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gps_points', to='logistics.delivery')),
            ],
            options={
                'db_table': 'gps_tracking',
                'ordering': ['-timestamp', 'tracking_id'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('maintenance_id', models.AutoField(db_column='maintenance_id', primary_key=True, serialize=False)),
                ('service_date', models.DateField(blank=True, null=True)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('cost', models.FloatField(default=0, help_text='Service cost in LKR')),
                ('next_service_date', models.DateField(blank=True, null=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='logistics.vehicle')),
            ],
            options={
                'db_table': 'maintenance_record',
                'ordering': ['-service_date', 'maintenance_id'],
            },
        ),
        migrations.CreateModel(
            name='FuelRecord',
            fields=[
                ('fuel_id', models.AutoField(db_column='fuel_id', primary_key=True, serialize=False)),
                ('fuel_type', models.CharField(choices=[('petrol', 'Petrol'), ('diesel', 'Diesel'), ('cng', 'CNG')], default='diesel', max_length=20)),
                ('quantity', models.FloatField(help_text='Quantity in litres')),
                ('cost', models.FloatField(help_text='Total cost in LKR')),
                ('fuel_date', models.DateField(blank=True, null=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_records', to='logistics.vehicle')),
            ],
            options={
                'db_table': 'fuel_record',
                'ordering': ['-fuel_date', 'fuel_id'],
            },
        ),
    ]
