"""
Django settings for pmb_bk project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from datetime import timedelta
from pathlib import Path
from decouple import Csv, config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('DJANGO_SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DJANGO_DEBUG', default=False, cast=bool)

ALLOWED_HOSTS = config('DJANGO_ALLOWED_HOSTS', default='localhost,127.0.0.1', cast=Csv())

# Needed once this runs behind Azure App Service (or any proxy that
# terminates TLS and forwards plain HTTP internally) — otherwise Django
# thinks every request is insecure HTTP, which breaks CSRF and secure
# cookies. Harmless locally, where there's no such proxy in front of it.
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Django 4+ requires the scheme-qualified origin of any host allowed to
# submit CSRF-protected (session-authenticated) POSTs — matters for the
# Django admin site once it's reachable at a real domain instead of
# localhost. The API itself uses JWT auth, which isn't subject to this.
CSRF_TRUSTED_ORIGINS = config('CSRF_TRUSTED_ORIGINS', default='', cast=Csv())

# Django's `check --deploy` flags these by default when off — meaningless
# (and actively wrong) locally over plain HTTP, so tied to DEBUG rather
# than hardcoded, same as the STORAGES backend choice above.
#
# SECURE_SSL_REDIRECT is independently overridable (unlike the others
# below) because a reverse-proxy deployment on the same host as this
# process — e.g. Nginx terminating TLS in front of Gunicorn on the same
# VM — needs plain-HTTP loopback traffic (health checks, server-side
# fetches from a Next.js frontend running on the same machine) to reach
# Django directly without being redirected into a TLS port Gunicorn never
# actually serves. Nginx already enforces HTTPS for real public/browser
# traffic in that setup, so Django's own redirect is redundant there
# anyway — set DJANGO_SECURE_SSL_REDIRECT=False for that case.
SECURE_SSL_REDIRECT = config('DJANGO_SECURE_SSL_REDIRECT', default=not DEBUG, cast=bool)
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG
SECURE_HSTS_SECONDS = 0 if DEBUG else 31536000
SECURE_HSTS_INCLUDE_SUBDOMAINS = not DEBUG
SECURE_HSTS_PRELOAD = not DEBUG


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'channels',  # must precede staticfiles -- lets Channels override `runserver` to serve ASGI locally too
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',  # tracks/revokes refresh tokens (used by logout/force-logout)
    'corsheaders',  # allows the separately-hosted Next.js frontend to call this API cross-origin
    'accounts',
    'farmers',
    'mills',
    'purchases',
    'sysops',
    'notifications',  # real-time WebSocket notification push (no models)
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # serves static files directly — must stay right after SecurityMiddleware
    'corsheaders.middleware.CorsMiddleware',
    'sysops.middleware.MaintenanceModeMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'accounts.middleware.UpdateLastActivityMiddleware',
]

ROOT_URLCONF = 'pmb_bk.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'pmb_bk.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'HOST': config('DB_HOST'),
        'PORT': config('DB_PORT', default='5432'),
        'NAME': config('DB_NAME', default='postgres'),
        'USER': config('DB_USER'),
        'PASSWORD': config('DB_PASSWORD'),
        # Defaults to 0 (reconnect every request) because Django's dev
        # server (`manage.py runserver`) spawns an unbounded thread per
        # request -- each thread would park its own persistent connection
        # open for the full duration, which previously blew straight
        # through Supabase's session-pooler cap of 15 concurrent
        # connections ("max clients reached"). Safe to raise behind a real
        # WSGI server with a small fixed worker count (e.g. gunicorn
        # --workers 4, see deploy/gunicorn.service -- 4 workers means at
        # most 4 connections held open, well under the cap), so production
        # sets DB_CONN_MAX_AGE=60 to skip the connection-setup handshake
        # (TCP+TLS+auth to a remote DB) on every single request.
        'CONN_MAX_AGE': config('DB_CONN_MAX_AGE', default=0, cast=int),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'  # collectstatic's target dir; whitenoise serves from here

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# User-uploaded media (profile pictures, generated PDFs) needs storage that
# survives restarts/redeploys and works across multiple instances — local
# disk (FileSystemStorage, fine for local dev) doesn't guarantee that on
# Azure App Service. Set these three once an Azure Storage Account exists
# to switch media over to Blob Storage; leave them blank to keep using local
# disk (e.g. for local dev, or a single-instance deployment with no need
# for shared storage yet).
AZURE_ACCOUNT_NAME = config('AZURE_ACCOUNT_NAME', default='')
AZURE_ACCOUNT_KEY = config('AZURE_ACCOUNT_KEY', default='')
AZURE_CONTAINER = config('AZURE_CONTAINER', default='media')

STORAGES = {
    'default': (
        {'BACKEND': 'storages.backends.azure_storage.AzureStorage'}
        if AZURE_ACCOUNT_NAME
        else {'BACKEND': 'django.core.files.storage.FileSystemStorage'}
    ),
    'staticfiles': {
        # Manifest storage requires collectstatic to have already run, which
        # never happens in local dev — falls back to the plain storage
        # runserver already knows how to serve so nothing breaks locally.
        'BACKEND': (
            'whitenoise.storage.CompressedManifestStaticFilesStorage'
            if not DEBUG
            else 'django.contrib.staticfiles.storage.StaticFilesStorage'
        ),
    },
}


# Tells Django to use the custom email-based User model (accounts.models.User)
# instead of its own built-in username-based one.
AUTH_USER_MODEL = 'accounts.User'

# Comma-separated list of allowed frontend origins, read from the
# environment (e.g. the Next.js dev server / production domain).
CORS_ALLOWED_ORIGINS = config('CORS_ALLOWED_ORIGINS', cast=Csv())

# Vercel preview deployments get a fresh, unpredictable URL per branch/PR
# (e.g. smart-pmb-git-my-branch-username.vercel.app), so an exact-match
# CORS_ALLOWED_ORIGINS entry can't cover them. This matches any of them by
# pattern instead — set via env once the real Vercel project name is known;
# left blank (the default), no regex is added and only CORS_ALLOWED_ORIGINS
# applies, same as before.
CORS_ALLOWED_ORIGIN_REGEXES = config('CORS_ALLOWED_ORIGIN_REGEXES', default='', cast=Csv())

# Required so the browser will send/receive the httpOnly auth cookies the
# frontend stores the JWT pair in.
CORS_ALLOW_CREDENTIALS = True

# DRF defaults: every endpoint authenticates via JWT (the Authorization:
# Bearer header the frontend attaches) and requires login unless a view
# explicitly opts out with permission_classes = [AllowAny].
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        # Custom subclass that eagerly loads role/permissions — see
        # accounts/authentication.py's docstring for why.
        'accounts.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_THROTTLE_RATES': {
        # IP-based cap on login attempts, independent of the per-account
        # lockout in CustomTokenObtainPairSerializer — this slows down an
        # attacker hammering many different accounts from one IP.
        'login': '10/min',
        # Caps how fast one IP can trigger forgot-password emails — this
        # endpoint has no per-account lockout of its own (it's unauthenticated
        # by definition), so this is its only abuse/spam guard.
        'password_reset': '5/min',
        # Caps how fast one admin can trigger impersonation-OTP emails to a
        # target — request_impersonation_otp had no throttle at all before,
        # unlike every other OTP-emailing endpoint in this file.
        'impersonation_otp': '10/min',
        # The scheduler calls this at most once a day — a generous cap that
        # still bounds how fast a leaked/guessed INTERNAL_TASK_SECRET could
        # be brute-forced or used to spam the job.
        'internal_task': '10/hour',
    },
    # Logs every exception any view raises to ErrorLog (see
    # sysops/exception_handler.py) before falling back to DRF's normal
    # response handling — general-purpose error visibility across the
    # whole API, not just the hand-picked AuditLog actions.
    'EXCEPTION_HANDLER': 'sysops.exception_handler.custom_exception_handler',
}

# Base URL of the Next.js frontend, used to build links embedded in
# outgoing emails (e.g. the email-confirmation link in accounts/emails.py).
FRONTEND_URL = config('FRONTEND_URL', default='http://localhost:3000')

# Public base URL of this backend itself, used to build absolute media URLs
# (profile pictures, license application documents) that get sent to the
# browser. Deliberately NOT request.build_absolute_uri() -- the frontend
# calls this API server-to-server, straight over 127.0.0.1:8000 rather than
# through nginx/the public hostname (see NEXT_PUBLIC_DJANGO_API_URL), so a
# request-based host would bake that internal, browser-unreachable address
# into the URL instead of the real public one.
BACKEND_URL = config('BACKEND_URL', default='http://localhost:8000')

# Defaults to printing emails to the console in development; set real SMTP
# credentials via environment variables for production email delivery.
EMAIL_BACKEND = config(
    'EMAIL_BACKEND', default='django.core.mail.backends.console.EmailBackend'
)
EMAIL_HOST = config('EMAIL_HOST', default='')
EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')
EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=True, cast=bool)
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default='no-reply@smartpmb.local')
# Without this, a stalled SMTP connection (network hiccup, provider
# throttling) hangs the socket indefinitely instead of failing — and since
# some call sites send email on a background thread (see accounts/emails.py
# send_async), a hung thread would otherwise never get cleaned up.
EMAIL_TIMEOUT = config('EMAIL_TIMEOUT', default=10, cast=int)

# Text.lk SMS gateway, used to deliver the forgot-password OTP when the user
# picks the SMS channel (accounts/sms.py). Left blank, send_otp_sms logs the
# code instead of sending it, so the rest of the OTP flow stays testable
# without a Text.lk account.
TEXTLK_API_TOKEN = config('TEXTLK_API_TOKEN', default='')
TEXTLK_SENDER_ID = config('TEXTLK_SENDER_ID', default='')
TEXTLK_API_URL = config('TEXTLK_API_URL', default='https://app.text.lk/api/v3/sms/send')

# Stripe (test mode) — powers the system-change-request payment flow
# (sysops.views.SystemChangeRequestViewSet.accept/StripeWebhookView). Left
# blank, accept() fails with a clear error instead of silently no-oping, so
# a missing key is caught immediately rather than discovered at payment time.
STRIPE_SECRET_KEY = config('STRIPE_SECRET_KEY', default='')
STRIPE_WEBHOOK_SECRET = config('STRIPE_WEBHOOK_SECRET', default='')

# Shared secret an external scheduler (see .github/workflows/capacity-forecast-schedule.yml)
# presents to POST /api/internal/run-capacity-forecasts/ instead of a JWT —
# same "unauthenticated caller, secret-verified" shape as the Stripe webhook
# above. Left blank, that view refuses every request (fails closed) rather
# than accepting an unauthenticated trigger by default.
INTERNAL_TASK_SECRET = config('INTERNAL_TASK_SECRET', default='')

# Real-time notification push (see notifications app + accounts/signals.py):
# whenever a Message is created, a post_save signal in THIS (WSGI) process
# makes a loopback HTTP call to the separate ASGI process (Daphne, see
# deploy/daphne.service) that actually holds the WebSocket connections, so
# it can fan the message out to the right connected browser(s). Same
# "unauthenticated caller, secret-verified" shape as INTERNAL_TASK_SECRET
# above. Both left blank by default -- accounts/signals.py just no-ops in
# that case, and the notification bell falls back to its ~2 minute poll,
# so this is entirely optional for local dev.
WS_PUSH_URL = config('WS_PUSH_URL', default='')
WS_INTERNAL_SECRET = config('WS_INTERNAL_SECRET', default='')

ASGI_APPLICATION = 'pmb_bk.asgi.application'

# In-memory, not Redis: only one Daphne process ever runs (see
# deploy/daphne.service), so every WebSocket connection this app ever
# needs to reach is already held in that single process's own memory --
# no cross-process message bus needed at this app's scale.
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels.layers.InMemoryChannelLayer',
    },
}

# Secret used to sign/verify JWTs; kept separate from SECRET_KEY so it can
# be rotated independently without invalidating Django's other signed data
# (sessions, password reset tokens, etc.).
JWT_SIGNING_KEY = config('JWT_SIGNING_KEY')

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=15),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    # Issues a new refresh token on every use, and blacklists the one it
    # replaced — limits how long a stolen refresh token stays useful.
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': JWT_SIGNING_KEY,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'sub',
}
