"""
Django settings for pmb_bk project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from datetime import timedelta
from pathlib import Path
from decouple import Csv, config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('DJANGO_SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DJANGO_DEBUG', default=False, cast=bool)

ALLOWED_HOSTS = ['localhost', '127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',  # tracks/revokes refresh tokens (used by logout/force-logout)
    'corsheaders',  # allows the separately-hosted Next.js frontend to call this API cross-origin
    'accounts',
    'farmers',
    'sysops',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'accounts.middleware.UpdateLastActivityMiddleware',
]

ROOT_URLCONF = 'pmb_bk.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'pmb_bk.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'HOST': config('DB_HOST'),
        'PORT': config('DB_PORT', default='5432'),
        'NAME': config('DB_NAME', default='postgres'),
        'USER': config('DB_USER'),
        'PASSWORD': config('DB_PASSWORD'),
        # CONN_MAX_AGE intentionally left at the default (0, reconnect
        # every request) — tried 60s to cut down on the remote DB's
        # connection-setup latency, but Django's dev server spawns an
        # unbounded thread per request, so each thread parked its own
        # persistent connection open for the full 60s. That blew straight
        # through Supabase's session-pooler cap of 15 concurrent
        # connections and locked the whole app out with
        # "max clients reached". Safe to revisit behind a real WSGI
        # server with a small fixed worker count (e.g. gunicorn
        # --workers 4), or by pointing DB_HOST/DB_PORT at Supabase's
        # transaction pooler instead of the session pooler.
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# Tells Django to use the custom email-based User model (accounts.models.User)
# instead of its own built-in username-based one.
AUTH_USER_MODEL = 'accounts.User'

# Comma-separated list of allowed frontend origins, read from the
# environment (e.g. the Next.js dev server / production domain).
CORS_ALLOWED_ORIGINS = config('CORS_ALLOWED_ORIGINS', cast=Csv())
# Required so the browser will send/receive the httpOnly auth cookies the
# frontend stores the JWT pair in.
CORS_ALLOW_CREDENTIALS = True

# DRF defaults: every endpoint authenticates via JWT (the Authorization:
# Bearer header the frontend attaches) and requires login unless a view
# explicitly opts out with permission_classes = [AllowAny].
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        # Custom subclass that eagerly loads role/permissions — see
        # accounts/authentication.py's docstring for why.
        'accounts.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_THROTTLE_RATES': {
        # IP-based cap on login attempts, independent of the per-account
        # lockout in CustomTokenObtainPairSerializer — this slows down an
        # attacker hammering many different accounts from one IP.
        'login': '10/min',
    },
    # Logs every exception any view raises to ErrorLog (see
    # sysops/exception_handler.py) before falling back to DRF's normal
    # response handling — general-purpose error visibility across the
    # whole API, not just the hand-picked AuditLog actions.
    'EXCEPTION_HANDLER': 'sysops.exception_handler.custom_exception_handler',
}

# Base URL of the Next.js frontend, used to build links embedded in
# outgoing emails (e.g. the email-confirmation link in accounts/emails.py).
FRONTEND_URL = config('FRONTEND_URL', default='http://localhost:3000')

# Defaults to printing emails to the console in development; set real SMTP
# credentials via environment variables for production email delivery.
EMAIL_BACKEND = config(
    'EMAIL_BACKEND', default='django.core.mail.backends.console.EmailBackend'
)
EMAIL_HOST = config('EMAIL_HOST', default='')
EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')
EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=True, cast=bool)
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default='no-reply@smartpmb.local')

# Secret used to sign/verify JWTs; kept separate from SECRET_KEY so it can
# be rotated independently without invalidating Django's other signed data
# (sessions, password reset tokens, etc.).
JWT_SIGNING_KEY = config('JWT_SIGNING_KEY')

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=15),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    # Issues a new refresh token on every use, and blacklists the one it
    # replaced — limits how long a stolen refresh token stays useful.
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': JWT_SIGNING_KEY,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'sub',
}
