# Generated by Django 6.0.6 on 2026-07-23 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_manage_transport_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='target_role',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('pmb_officer', 'PMB Officer')], max_length=20, null=True),
        ),
    ]
