# Generated by Django 6.0.6 on 2026-07-26 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_driver_vehicle_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notify_in_app_messages',
            field=models.BooleanField(default=True),
        ),
    ]
