# Generated by Django 6.0.6 on 2026-07-28 06:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def copy_existing_grants(apps, schema_editor):
    """
    Copies every existing (role_id, permission_id) pair out of the
    auto-generated `accounts_role_permissions` join table into the new
    explicit RolePermission table, before the AlterField below drops that
    implicit table — otherwise every role's current permission grants
    would be silently lost. granted_by is left null (unknown for grants
    made before this model existed); granted_date defaults to now.
    """
    RolePermission = apps.get_model("accounts", "RolePermission")
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("SELECT role_id, permission_id FROM accounts_role_permissions")
        rows = cursor.fetchall()
    RolePermission.objects.bulk_create(
        [RolePermission(role_id=role_id, permission_id=permission_id) for role_id, permission_id in rows],
        ignore_conflicts=True,
    )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_user_must_change_password_licenseapplication'),
    ]

    operations = [
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granted_date', models.DateTimeField(auto_now_add=True)),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.permission')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.role')),
            ],
            options={
                'unique_together': {('role', 'permission')},
            },
        ),
        migrations.RunPython(copy_existing_grants, noop_reverse),
        # Django won't let AlterField add `through=` to an M2M directly (it
        # refuses to alter to/from M2M or change its `through`) — the real
        # schema change is just "drop the now-unused auto-generated join
        # table", the field itself is already backed by RolePermission
        # (created above), so this only needs a state change plus an
        # explicit drop of the old table.
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    "DROP TABLE accounts_role_permissions",
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.AlterField(
                    model_name='role',
                    name='permissions',
                    field=models.ManyToManyField(blank=True, related_name='roles', through='accounts.RolePermission', to='accounts.permission'),
                ),
            ],
        ),
    ]
