# Generated by Django 6.0.6 on 2026-07-28 07:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_role_permission_through'),
        ('farmers', '0016_transaction_log_inventory'),
    ]

    operations = [
        migrations.CreateModel(
            name='PmbOfficer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_no', models.CharField(max_length=50, unique=True)),
                ('nic', models.CharField(blank=True, max_length=20)),
                ('designation', models.CharField(blank=True, max_length=100)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('contact_number', models.CharField(blank=True, max_length=20)),
                ('joined_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pmb_officers', to='farmers.district')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pmb_officer_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
