# Generated by Django 6.0.6 on 2026-08-01 19:49

import accounts.constants
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_role_dashboard_widgets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='dashboard_widgets',
            field=models.JSONField(blank=True, default=accounts.constants.default_officer_dashboard_widgets),
        ),
    ]
