# Generated by Django 6.0.6 on 2026-08-04 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_impersonate_users_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='licenseapplication',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='license_application_documents/%Y/%m/'),
        ),
    ]
