# Generated by Django 6.0.6 on 2026-08-13 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_licenseapplication_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='licenseapplication',
            name='license_number',
            field=models.CharField(blank=True, max_length=40, null=True, unique=True),
        ),
    ]
