# Generated by Django 6.0.6 on 2026-08-13 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_access_pmb_officer_portal_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='licenseapplication',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='license_application_documents/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='licenseapplication',
            name='license_number',
            field=models.CharField(blank=True, max_length=40, null=True, unique=True),
        ),
    ]
